// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicAuth.Domain.Entites;

public partial class Endpoint
{
    public string EndpointId { get; set; }

    public string EndpointName { get; set; }
}