// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicAuth.Domain.Entites;

public partial class User_Role
{
    public int SeqNo { get; set; }

    public string UserId { get; set; }

    public string RoleId { get; set; }
}