// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SemaphoreSlimDemo.Models;

public partial class SemaphoreSlimTest
{
    public int SeqNo { get; set; }

    public DateTime CreateTime { get; set; }
}