// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HTTPClient.Entites;

public partial class HttpClientLog
{
    public int RecordNo { get; set; }

    public string FromRequestUri { get; set; }

    public string HttpMethod { get; set; }

    public string ReuqestUri { get; set; }

    public string Query { get; set; }

    public string RequestDefaultHeaders { get; set; }

    public string RequestHeaders { get; set; }

    public string RequestBody { get; set; }

    public string ResponseStatus { get; set; }

    public string ResponseHeaders { get; set; }

    public string ResponseBody { get; set; }

    public DateTime Time { get; set; }
}