// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HTTPClient.Entites;

public partial class TodoContext : DbContext
{
    public TodoContext(DbContextOptions<TodoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HttpClientLog> HttpClientLog { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HttpClientLog>(entity =>
        {
            entity.HasKey(e => e.RecordNo);

            entity.Property(e => e.FromRequestUri).IsUnicode(false);
            entity.Property(e => e.HttpMethod)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Query).IsUnicode(false);
            entity.Property(e => e.RequestBody).IsUnicode(false);
            entity.Property(e => e.RequestDefaultHeaders).IsUnicode(false);
            entity.Property(e => e.RequestHeaders).IsUnicode(false);
            entity.Property(e => e.ResponseBody).IsUnicode(false);
            entity.Property(e => e.ResponseHeaders).IsUnicode(false);
            entity.Property(e => e.ResponseStatus).IsUnicode(false);
            entity.Property(e => e.ReuqestUri).IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}